### ISSUE TITLE
caleydo_data_hdf dependency

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/taco_server#1]
why does taco_server needs to have a dependency to caleydo_data_hdf?

**Comment by thinkh** [comment]
Because the TCGA files we are using are h5 files.

**Comment by sgratzl** [comment]
but does the source code depend on the other plugin or should it just be linked to it during product composition?

**Comment by thinkh** [comment]
No, we need caleydo_data_hdf for loading the h5 files.

I removed the caleydo_data_hdf directory and restarted the server for testing. The result is that I get an internal server error and the h5 files are not listed.

**Comment by sgratzl** [comment]
I think we are talking about different things: From my point of view the taco "product" includes the caleydo_data_hdf plugin to read h5 datasets. However, the taco_server itself doesn't care how the datasets are stored, since it works against the generic dataset api.

**Comment by thinkh** [comment]
Ok. But to work with h5 datasets in TaCo I need the caleydo_data_hdf dependency; also in development and not only as product.

**Comment by thinkh** [comment]
If you want to use hdf files install the phovea_data_hdf separatly running the [install commands](https://github.com/phovea/phovea_data_hdf/#installation).
